### PR TITLE
Fix for #43 when .2 was not parsing is a Real Literal.

### PR DESCRIPTION
**Pull request by JustinRChou**
Fix for #43 when .2 was not parsing is a Real Literal.
Added additional Unit Tests for the new parsing.
Not sure what went wrong is the spacings.

### CODE REVIEW

**Comment by davideicardi** [comment]
Thanks very much for your pull request! 
Can I just ask you do leave the tabs instead of changing it to spaces? Otherwise we have hundreds of these kind of changes. I usually prefer tabs because are more configurable for each developer, but I know that this is a subjective argument 😄 

I think that there are some configuration on git that can handle these scenarios...

**Comment by JustinRChou** [comment]
Seems like I fixed the spacing diffs.

And it turns out that my fix was failing on the new unit tests for .2f and .2m formats.

**Comment by davideicardi** [comment]
Thanks @JustinRChou !
I will integrate these changes in the next release.

**Comment by davideicardi** [comment]
Thanks, merged in version 1.3.4.7

**Pull request merged**
