### PR TITLE
Add HexLiteral & Nullable Type

### PR DESCRIPTION
**Pull request by SaiedRahimy**
Add HexLiteral & add (Nullable Type)(Fix Error  "The binary operator AndAlso is not defined for the types 'System.Nullable`1[System.Boolean] " )

Co-Authored-By: Saied Rahimy <saiedrahimy@users.noreply.github.com>

### CODE REVIEW

**Comment by SaiedRahimy** [comment]
hi, pls check
25d>=12f
(int?)null>=12

**Comment by davideicardi** [comment]
Thanks for your help!

Can you just remove the ` WinFroemTest` project from the commit? I think it is not related to the fix right?

**Comment by SaiedRahimy** [comment]
You're welcome.
Yes, Sure

**Comment by davideicardi** [comment]
@SaiedRahimy 
It is possible for you to use the same indentation (`tab`)? Otherwise as you can see a lot of changes are listed but are problably just indentation changes. This can help me to review the PR better.
thanks!

**Comment by davideicardi** [comment]
I think that this problem is now fixed with #124 . Open again the PR in case it is not yet fixed...

**Pull request closed without merging**
