### PR TITLE
Improved indexing

### LINKED ISSUE #39: Indexed property setter not working
Hi, can anything be done about the indexed property setter not working. In both examples below the following exception occurs:

An unhandled exception of type 'System.ArgumentException' occurred in System.Core.dll.
Additional information: Expression must be writeable

Code:

`var interpreter = new Interpreter();

```
        var arr = new[] { 1 };
        arr[0] = 2;
        interpreter.SetVariable("arr", arr);
        interpreter.Eval("arr[0] = 3");

        var list = new List<int>(new[] { 1 });
        list[0] = 2;
        interpreter.SetVariable("list", list);
        interpreter.Eval("list[0] = 3");`
```

Thanks.

### PR DESCRIPTION
**Pull request by btnlq**
- Support array element assignment 
- Support indexing of multi-dimensional arrays
- Support indexer assignment 

Partially resolve #39

### CODE REVIEW

**Comment by davideicardi** [comment]
Thanks @btnlq !
Why it is only partially solved? What is missing?

**Comment by btnlq** [comment]
Issue #39 describes three unrelated problems:
1) Variable assignment (`GitHub_Issue_39_Simple_Reassignment`)
2) Array element assignment (`GitHub_Issue_39_Array_Reassignment`)
3) Indexer assignment (`GitHub_Issue_39_List_Reassignment`)

This pull request solves the second problem. Later I will try to deal with the third problem.

**Comment by btnlq** [comment]
@davideicardi, done!

I fixed the third problem (support for indexer assignment). I also added support for multidimensional arrays.

**Comment by davideicardi** [comment]
Great pull request! Very good work.

Just a quick question, do you think that the `AssignmentOperators` is always respected also inside these new workflow? I think it is important for security reason. In some context you don't want to allow expressions that modify data ...

**Comment by btnlq** [comment]
When a token `'='` is detected, `AssignmentOperators` is checked first of all. My changes did not break this behavior. But it’s impossible to prevent objects from being modified using methods like `Dictionary.Add` or `List.Sort`.

**Comment by davideicardi** [comment]
Just merged, v2.3.0 Thanks again!

**Pull request merged**
