### PR TITLE
added support for null enum

### PR DESCRIPTION
**Pull request by igor-smi**
When parsing an expression containing a type of null enum, an error occurs. I tried to fix it.

### CODE REVIEW

**Comment by davideicardi** [comment]
Thanks @igor-smi !
Can I ask you to include a unit test to test and describe the new feature?

**Comment by igor-smi** [comment]
Added tests.

In what format and where should the function description be included?

**Comment by davideicardi** [comment]
@igor-smi 
Sorry for late response...

> In what format and where should the function description be included?
I mean if you can just explain here in the PR a little better your problem and solution. Just to understand exactly your use case.

Also can you please use tab indentation like the rest of the project? Just to avoid mixed indentation...
thanks!

**Comment by davideicardi** [comment]
I think that this problem is now fixed with #124 . Open again the PR in case it is not yet fixed...

**Pull request closed without merging**
